import type { GameState } from "../types";

export const initialState: GameState = {
  currentScreen: "title",
  userData: {
    gold: 0,
    ownedCards: [],
  },
  phase: "DRAW",
  players: [],
  monsters: [],
  currentPlayerIndex: 0,
  turn: 1,
  level: 1,
  round: 1,
  maxRounds: 6,
  environment: null,
  selectedCardId: null,
  selectedTargetId: null,
  playerSelections: [],
  drawnCards: [],
  log: [],
  selectedClasses: [],
  heroNames: [],
  deckBuildingPlayerIndex: 0,
  availableCards: [],
  selectedDeckCards: [],
  rewardPlayerIndex: 0,
  rewardCards: [],
  selectedRewardCardId: null,
  shopPlayerIndex: 0,
  shopCards: [],
  selectedShopCardId: null,
  roundGoldEarned: 0,
  animation: {
    isAnimating: false,
    diceRoll: null,
    diceRolling: false,
    actionMessages: [],
    damageNumbers: [],
  },
  gameSpeed: "normal",
  skipAnimations: false,
  savedParty: null,
  enhanceMode: false,
};
